Repository spacetelescope/slitlessutils, pull requests merged in 2025-03, with the labels that each got.

#88 Update dependencies
  .github/workflows/ci_tests.yml
  pyproject.toml
  pytest.ini
  slitlessutils/core/photometry/avefnu.py
  slitlessutils/core/photometry/band.py
  slitlessutils/core/preprocess/background/background.py
  slitlessutils/core/preprocess/crrej/laplace.py
  slitlessutils/core/sources/operators.py
Labels: infrastructure, testing

#89 Remove windows tests from CI
  .github/workflows/ci_tests.yml
Labels: testing

#86 Retrieve correct master background for subarray data
  slitlessutils/core/preprocess/background/background.py
Labels: enhancement

#93 Fix trapezoid call
  slitlessutils/core/photometry/avefnu.py
Labels: bug, affects-dev

#94 Fix numpy 2.0 issues
  slitlessutils/core/tables/attributes.py
  slitlessutils/core/utilities/indices.py
Labels: bug

#95 Update python requirement in installation instructions
  docs/install.rst
Labels: documentation
